### ISSUE TITLE
How to sign an XML choose some settings?

### ISSUE THREAD

**Issue by faelp22** [moov-io/signedxml#52]
Hello everyone, could anyone create an example of how to sign an XML using the following settings?

Hash
http://www.w3.org/2000/09/xmldsig#sha1

Signature
http://www.w3.org/2000/09/xmldsig#rsa-sha1

Canonicalization Methods/Transforms
http://www.w3.org/TR/2001/REC-xml-c14n-20010315

I've tried to do it, but I can't understand it.

**Comment by adamdecaf** [comment]
Your [`Signature` element](https://github.com/moov-io/rtp20022/blob/master/gen/xmldsig/xmldsig.go#L12) would have those settings included. The XML specifications have all of the values, but they're [in code as well](https://github.com/russellhaering/goxmldsig/blob/main/xml_constants.go#L45)

Then you'll [marshal and sign the xml](https://github.com/moov-io/signedxml/blob/master/signer.go#L47-L65). See tests in this repository for examples.

**Comment by jsdaniell** [comment]
I couldn't find any example on the `tests` folder :/

**Comment by adamdecaf** [comment]
You can specify those in the xml - https://github.com/moov-io/signedxml/blob/master/tests/testdata/issue55.xml 

Then create a Signer and call .Sign - https://github.com/moov-io/signedxml/blob/master/tests/issue55_test.go#L22

**Comment by jsdaniell** [comment]
Can you help me to do this using the `Signature` struct that I created? Here's my code:

```go
func SignXML(xpath, canonicalizationAlgorithm, certificate, digestAlgorithm, publicKey, privateKey, xmlString string, transforms []string) error {
	if digestAlgorithm == "" {
		digestAlgorithm = "http://www.w3.org/2000/09/xmldsig#sha1"
	}

	if len(transforms) == 0 {
		transforms = []string{
			"http://www.w3.org/2000/09/xmldsig#enveloped-signature",
			"http://www.w3.org/TR/2001/REC-xml-c14n-20010315#WithComments",
		}
	}

	if certificate == "" {
		certificate = models.GetX509Cert(publicKey)
	}

	if canonicalizationAlgorithm == "" {
		canonicalizationAlgorithm = dsig.CanonicalXML10WithCommentsAlgorithmId.String()
	}

	if publicKey == "" {
		p, err := GetPublicKeyFromFile()
		if err != nil {
			return err
		}

		publicKey = p
	}

	if privateKey == "" {
		p, err := GetPrivateKeyFromFile()
		if err != nil {
			return err
		}

		privateKey = p
	}

	if xpath == "" {
		return errors.New("xpath is required")
	}

	transformsTypes := xmldsig.TransformsType{Transform: make([]xmldsig.TransformType, len(transforms))}

	for i, t := range transforms {
		transformsTypes.Transform[i] = xmldsig.TransformType{
			Algorithm: t,
			XPath:     []*string{&xpath},
		}
	}

	sig := xmldsig.Signature{
		KeyInfo: &xmldsig.KeyInfoType{
			X509Data: []*xmldsig.X509DataType{
				{
					X509Certificate: &certificate,
				},
			},
		},
		SignedInfo: xmldsig.SignedInfoType{
			CanonicalizationMethod: xmldsig.CanonicalizationMethodType{
				Algorithm: canonicalizationAlgorithm,
			},
			Reference: []xmldsig.ReferenceType{
				{
					Transforms: &transformsTypes,
					DigestMethod: xmldsig.DigestMethodType{
						Algorithm: digestAlgorithm,
					},
				},
			},
		},
	}

	spew.Dump(sig)
	return nil
}
```

**Comment by adamdecaf** [comment]
What error are you getting?
